name = "cslib"
version = "0.1.0"
defaultTargets = ["Cslib"]
testDriver = "CslibTests"

[leanOptions]
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Cslib"
globs = "Cslib.*"

[[lean_lib]]
name = "CslibTests"
globs = "CslibTests.+"
